"""Regenerate the three static information pages. No runtime build needed."""
from pathlib import Path
from html import escape

root=Path(__file__).resolve().parents[1]/'public'
index=(root/'index.html').read_text(encoding='utf-8')
header=index[index.index('<header class="site-header">'):index.index('</header>')+9]
footer=index[index.index('<footer class="site-footer">'):index.index('</footer>')+9]
def page(name,title,body):
    h=header.replace(' aria-current="page"','').replace(f'href="{name}"',f'href="{name}" aria-current="page"')
    (root/name).write_text(f'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{escape(title)} – Informationen zum MailBaukasten von Internessi."><meta name="theme-color" content="#173b3f"><title>{escape(title)} · MailBaukasten</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"></head><body><a class="skip" href="#inhalt">Zum Inhalt springen</a>{h}<main id="inhalt" class="document">{body}</main>{footer}</body></html>''',encoding='utf-8')

page('anleitung.html','Eine Mail bauen. Ganz einfach.', '''
<p class="eyebrow">Die kurze Anleitung</p><h1>Von der Idee zur fertigen Mail.</h1><p class="lead">Sie brauchen keinen HTML-Code. Nur Ihre Nachricht. Der MailBaukasten kümmert sich um die Gestaltung – und Sie behalten die Kontrolle über Ihre Inhalte.</p>
<div class="doc-grid"><section class="doc-card"><span class="doc-tag">01 · Gestalten</span><h2>Den passenden Ton finden.</h2><p>Wählen Sie „Markant“ mit kräftigem Briefkopf oder den hellen „Briefstil“. Fünf Farbwelten, zwei Schriftstile und drei Abstände stehen bereit. Ihre Eingaben bleiben bei jedem Wechsel erhalten.</p></section><section class="doc-card"><span class="doc-tag">02 · Schreiben</span><h2>Ihre Inhalte einsetzen.</h2><p>Unter „Inhalte“ öffnen Sie die einzelnen Bausteine. Ersetzen Sie die Beispiele durch eigene Texte. Schalten Sie nicht benötigte Bereiche aus. Ihre Texte bleiben dabei erhalten. Themen und Schritte lassen sich ergänzen oder entfernen.</p></section><section class="doc-card"><span class="doc-tag">03 · Ansehen</span><h2>Änderungen sofort sehen.</h2><p>Rechts sehen Sie das Ergebnis live. Mit „Mobil“ prüfen Sie eine schmale Ansicht. Auf kleinen Geräten wechseln Sie über „Bearbeiten“ und „Vorschau“. Die abschließende Gesamtansicht öffnen Sie mit „Vorschau &amp; Download“.</p></section><section class="doc-card"><span class="doc-tag">04 · Speichern</span><h2>Fertig für den nächsten Schritt.</h2><p>„HTML speichern“ lädt eine eigenständige Mailvorlage herunter. Vorher weist eine kurze Prüfung auf fehlende Angaben und Beispieltexte hin. Diese Prüfung entscheidet nicht, ob Sie eine Nachricht versenden dürfen.</p></section></div>
<section class="doc-card"><h2>HTML oder Entwurf – welche Datei wofür?</h2><p><strong>HTML-Vorlage:</strong> Die fertig gestaltete E-Mail zum Import in ein geeignetes Mailprogramm oder Versandsystem. Ausgeschaltete Bereiche sind darin nicht enthalten.</p><p><strong>JSON-Entwurf:</strong> Ihre bearbeitbare Arbeitsdatei mit allen Texten, ausgeblendeten Bausteinen und Einstellungen. „Entwurf sichern“ lädt sie herunter, „Entwurf laden“ öffnet sie wieder. Die HTML-Datei lässt sich nicht zurück in einen Entwurf importieren.</p><p><strong>Auf diesem Gerät merken:</strong> Auf Wunsch speichert der Browser Ihren Entwurf lokal. Auf gemeinsam genutzten Geräten besser ausgeschaltet lassen. Browserdaten löschen oder „Neu beginnen“ entfernt den gemerkten Entwurf. Eine Entwurfsdatei ist die verlässlichere Sicherung.</p></section>
<section class="doc-card"><h2>Wie kommt die Vorlage in eine E-Mail?</h2><ol><li>Speichern Sie die HTML-Datei auf Ihrem Computer.</li><li>Öffnen Sie im verwendeten Mail- oder Newsletterprogramm die Funktion zum Importieren einer HTML-Vorlage beziehungsweise zum Bearbeiten des HTML-Quelltexts. Nicht jedes Programm bietet das an.</li><li>Importieren Sie die Datei oder setzen Sie deren Quelltext in den dafür vorgesehenen HTML-Editor ein. Den HTML-Code nicht in ein normales Textfeld einfügen.</li><li>Tragen Sie den Betreff separat ein. Stellen Sie den richtigen Absender, die Antwortadresse und die zulässigen Empfänger ein.</li><li>Versenden Sie zunächst eine Testmail an sich selbst und kontrollieren Sie Darstellung, Links, Abmeldung und Handyansicht.</li></ol><p>Die genaue Vorgehensweise hängt vom Programm und dessen Version ab. Eine HTML-Datei als Anhang zu versenden zeigt sie nicht automatisch als gestalteten Mailinhalt. Für Outlook wird hier keine spezielle OFT-Datei erzeugt.</p></section>
<div class="callout"><strong>Browser-Vorschau ist keine Versandgarantie.</strong><br>Mailprogramme können Schriften, Abstände, dunkle Darstellung oder Links anders behandeln. Besonders klassisches Outlook verwendet eine andere Darstellungstechnik. Der Export nutzt dafür Tabellen und Inline-Styles; eine Testmail bleibt trotzdem wichtig.</div>
<section class="doc-card"><h2>Was der MailBaukasten bewusst einfach hält</h2><p>Kein Versand, keine Empfängerlisten, keine Anmeldung, keine Tracking-Pixel und keine öffentlichen Links zu Ihren Entwürfen. Texte werden als Text behandelt; eigener HTML-Code wird nicht ausgeführt. Bilder und Dateianhänge sind in dieser Version nicht vorgesehen.</p><p>Die Links in der Vorschau dienen der Darstellung und sind nicht zum Navigieren gedacht. Prüfen Sie Zieladressen im Editor und später in der Testmail.</p><p><a href="./">Jetzt eine Mail bauen →</a> · <a href="recht.html">Vor dem Versand: E-Mail &amp; Recht</a></p></section>
''')

page('recht.html','E-Mail & Recht', '''
<p class="eyebrow">Bewusst gestalten. Verantwortlich versenden.</p><h1>Eine gute Mail braucht mehr als gutes Design.</h1><p class="lead">Wer darf angeschrieben werden? Was gehört in die Nachricht? Eine Orientierung für E-Mails in Deutschland – mit Links zu den maßgeblichen Quellen.</p><p class="sources">Stand: 21. September 2026 · Allgemeine Informationen, keine individuelle Rechtsberatung. Sonderfälle und andere Länder können zusätzliche Anforderungen mit sich bringen.</p>
<section class="doc-card"><span class="doc-tag">01 · Anlass klären</span><h2>Welche Nachricht möchten Sie senden?</h2><p>Eine persönliche Antwort oder eine notwendige Vertragsnachricht verfolgt einen anderen Zweck als ein Newsletter oder ein Verkaufsangebot. Entscheidend sind tatsächlicher Inhalt und Zweck, nicht die Bezeichnung. Zusätzliche Werbung kann auch eine sonst sachliche Nachricht rechtlich verändern. Für den Einzelfall die passende Rechtsgrundlage prüfen.</p><p class="sources">Einordnungshilfe: <a href="https://www.datenschutzkonferenz-online.de/media/oh/OH-Werbung_Februar%202022_final.pdf">Datenschutzkonferenz – Orientierungshilfe Direktwerbung (2022, PDF)</a>.</p></section>
<section class="doc-card"><span class="doc-tag">02 · Empfängerberechtigung</span><h2>Wen darf ich werblich anschreiben?</h2><p>E-Mail-Werbung erfordert grundsätzlich eine vorherige ausdrückliche Einwilligung – auch gegenüber Unternehmen. Eine veröffentlichte E-Mail-Adresse oder ein vermutetes Interesse genügt dafür nicht.</p><h3>Eng begrenzte Ausnahme: bestehende Kunden</h3><p>Ohne Einwilligung greift die Ausnahme nur, wenn <strong>alle vier Voraussetzungen</strong> erfüllt sind:</p><ol><li>Die Adresse wurde im Zusammenhang mit einem Verkauf an diesen Kunden erhalten.</li><li>Beworben werden eigene ähnliche Waren oder Dienstleistungen.</li><li>Der Kunde hat nicht widersprochen.</li><li>Bei der Erhebung und bei jeder Verwendung wird deutlich auf den jederzeitigen Widerspruch hingewiesen; außer üblichen Übermittlungskosten entstehen keine Kosten.</li></ol><p>Eine bloße Anfrage macht jemanden nicht automatisch zum Bestandskunden. Werbung darf den Absender nicht verbergen und benötigt eine gültige Adresse für Aufforderungen, die Zusendung einzustellen. Ein Abmeldelink ersetzt keine vorher erforderliche Einwilligung.</p><p class="sources">Quelle: <a href="https://www.gesetze-im-internet.de/uwg_2004/__7.html">§ 7 UWG, insbesondere Absätze 2 und 3</a>.</p></section>
<section class="doc-card"><span class="doc-tag">03 · Nachweis &amp; Abmeldung</span><h2>Einwilligung nachvollziehbar festhalten.</h2><p>Dokumentieren Sie, wer wann und wofür eingewilligt hat. Bei elektronischen Newsletter-Anmeldungen ist ein sauber protokolliertes Double-Opt-in-Verfahren ein wichtiger Weg zum Nachweis: Auf die Anmeldung folgt eine gesonderte Bestätigung. Allein eine gespeicherte IP-Adresse reicht nicht aus.</p><p class="sources">Quelle: <a href="https://www.datenschutzkonferenz-online.de/media/oh/OH-Werbung_Februar%202022_final.pdf">DSK – Direktwerbung, insbesondere Abschnitt 3.3 (PDF)</a>.</p><p>Eine Einwilligung muss widerrufbar sein. Einem Widerspruch gegen Direktwerbung ist nachzukommen; die Daten dürfen dann nicht weiter für diesen Zweck verwendet werden. Organisieren Sie Abmeldungen zuverlässig auch im eigentlichen Versandsystem. Der MailBaukasten verwaltet keine Verteiler und verarbeitet keine Abmeldungen.</p><p class="sources">Quelle: <a href="https://eur-lex.europa.eu/legal-content/DE/ALL/?uri=CELEX:32016R0679">DSGVO, Artikel 7 und 21</a>.</p></section>
<section class="doc-card"><span class="doc-tag">04 · Inhalt &amp; Absender</span><h2>Was muss in die Mail?</h2><p><strong>Klarer Absender und ehrlicher Betreff:</strong> Bei kommerzieller Kommunikation dürfen Identität und Werbecharakter nicht verschleiert werden. Angebote und ihre Bedingungen müssen transparent sein.</p><p class="sources">Quelle: <a href="https://www.gesetze-im-internet.de/ddg/__6.html">§ 6 DDG</a>.</p><p><strong>Angaben passend zur Rechtsform:</strong> Für Geschäftsbriefe einer GmbH sind unter anderem Rechtsform, Sitz, Registergericht, Registernummer und sämtliche Geschäftsführer erforderlich; gegebenenfalls kommt der Aufsichtsratsvorsitz hinzu. Bei eingetragenen Kaufleuten gelten eigene Angaben. Für andere Rechtsformen die jeweiligen Vorschriften prüfen. Ein allgemeiner Impressumslink ersetzt nicht automatisch die im Geschäftsbrief erforderlichen Angaben.</p><p class="sources">Quellen: <a href="https://www.gesetze-im-internet.de/gmbhg/__35a.html">§ 35a GmbHG</a> · <a href="https://www.gesetze-im-internet.de/hgb/__37a.html">§ 37a HGB</a>.</p><p><strong>Eigene Daten einsetzen:</strong> Verwenden Sie im Mailing Ihre Firma, Anschrift, Kontaktmöglichkeiten und erforderlichen Pflichtangaben. Das Internessi-Impressum gehört zum Betreiber dieses Generators, nicht zu Ihrem Unternehmen. Für geschäftsmäßige digitale Dienste gelten zusätzlich die Informationspflichten des DDG.</p><p class="sources">Quelle: <a href="https://www.gesetze-im-internet.de/ddg/__5.html">§ 5 DDG</a>.</p></section>
<section class="doc-card"><span class="doc-tag">05 · Datenschutz</span><h2>Adressen verantwortungsvoll verwenden.</h2><p>Die Verarbeitung personenbezogener Daten braucht eine Rechtsgrundlage. Beachten Sie Informationspflichten, insbesondere bei direkt oder von Dritten erhobenen Adressen. Gekaufte oder öffentlich auffindbare Kontaktdaten sind keine pauschale Versanderlaubnis.</p><p>Die datenschutzrechtliche Grundlage und die Zulässigkeit des Werbekanals müssen getrennt geprüft werden. Ein berechtigtes Interesse ersetzt nicht automatisch eine für E-Mail-Werbung erforderliche Einwilligung. Bei externen Versanddiensten sind außerdem deren Datenschutzbedingungen und gegebenenfalls eine Auftragsverarbeitung zu prüfen.</p><p class="sources">Quellen: <a href="https://eur-lex.europa.eu/legal-content/DE/ALL/?uri=CELEX:32016R0679">DSGVO, insbesondere Artikel 6, 13, 14 und 28</a> · <a href="https://commission.europa.eu/law/law-topic/data-protection/information-business-and-organisations/legal-grounds-processing-data/can-data-received-third-party-be-used-marketing_de">Europäische Kommission: Daten Dritter für Werbung</a>.</p></section>
<div class="callout"><strong>Vor dem Versand:</strong> Berechtigung der Empfänger klären, Beispielwerte ersetzen, Absenderangaben prüfen, Abmeldung testen und eine Testmail ansehen. Die Hinweise beim HTML-Download prüfen nur erkennbare Eingabelücken; sie erteilen keine rechtliche Freigabe.</div><p><a href="./">Zurück zum MailBaukasten →</a></p>
''')

page('datenschutz.html','Datenschutz im MailBaukasten', '''
<p class="eyebrow">Ihre Texte bleiben bei Ihnen.</p><h1>Datenschutz im MailBaukasten.</h1><p class="lead">Diese Hinweise ergänzen die Datenschutzerklärung von Internessi um die Funktionen des Generators. Stand: 21. September 2026.</p>
<section class="doc-card"><h2>Verantwortlicher und allgemeine Informationen</h2><p>Betreiber ist die Alarm4u.de GmbH, Meußlitzer Str. 58, 01259 Dresden, vertreten durch Geschäftsführer Frank Wolf. Kontakt: <a href="mailto:info@alarm4u.de">info@alarm4u.de</a>.</p><p>Informationen zu Hosting, Server-Protokollen, Kontaktaufnahme, Rechtsgrundlagen und Ihren Betroffenenrechten finden Sie in der <a href="https://www.internessi.de/rechtliches.php#datenschutz">Datenschutzerklärung von Internessi</a>. Das <a href="https://www.internessi.de/rechtliches.php#impressum">Impressum</a> steht dort ebenfalls bereit.</p></section>
<section class="doc-card"><h2>Bearbeitung und Vorschau</h2><p>Texte, Absenderangaben und Einstellungen werden im Browser verarbeitet. Der Generator überträgt diese Inhalte nicht an unseren Server. Er verwendet keine externen Schriftarten, Analysewerkzeuge oder Tracking-Pixel und versendet keine E-Mails. Der Seitenabruf selbst erzeugt die in der Internessi-Datenschutzerklärung beschriebenen Hosting-Protokolle.</p><p>Ohne eingeschaltete Merken-Funktion speichert die Anwendung Ihren Entwurf nicht dauerhaft. Beim Verlassen oder Neuladen kann er verloren gehen.</p></section>
<section class="doc-card"><h2>Freiwillig auf diesem Gerät merken</h2><p>Nur wenn Sie „Entwurf auf diesem Gerät merken“ aktivieren, speichert der Generator Ihre Inhalte und Einstellungen im lokalen Speicher Ihres Browsers (Local Storage). Zweck ist ausschließlich, Ihren Entwurf bei einem späteren Besuch wiederherzustellen. Es erfolgt keine Übertragung an uns und kein geräteübergreifender Abgleich.</p><p>Diese Speicherung ist freiwillig und zunächst ausgeschaltet. Der Entwurf bleibt bis zum Entfernen gespeichert. Deaktivieren der Funktion, „Neu beginnen“ oder Löschen der Website-Daten im Browser entfernt ihn. Die aktuell geöffneten Eingaben bleiben beim Deaktivieren erhalten. Auf gemeinsam genutzten Geräten können andere Personen desselben Browserprofils auf gemerkte Entwürfe zugreifen.</p></section>
<section class="doc-card"><h2>Entwurfsdateien und Downloads</h2><p>Eine gewählte JSON-Entwurfsdatei wird ausschließlich lokal im Browser gelesen. HTML- und JSON-Downloads werden dort erzeugt und an Ihrem gewählten Speicherort abgelegt. JSON-Dateien enthalten auch die Texte ausgeblendeter Bausteine. Bewahren Sie diese Dateien entsprechend ihrem Inhalt auf und teilen Sie sie nur bewusst.</p><p>Ein bereits heruntergeladener Entwurf wird durch „Neu beginnen“ nicht von Ihrem Computer gelöscht. Darum kümmern Sie sich in Ihrer Dateiverwaltung.</p></section>
<section class="doc-card"><h2>Externe Links und weitere Fragen</h2><p>Wenn Sie externe Links etwa zu Gesetzestexten oder zum öffentlichen GitHub-Repository öffnen, gelten die Datenschutzbedingungen des jeweiligen Anbieters. Links werden nicht vorab im Hintergrund geladen. Die HTML-Vorlagen enthalten keine Tracking-Funktion des MailBaukastens.</p><p>Für Ihre spätere Empfängerliste und den Versand sind Sie und gegebenenfalls Ihr Versanddienst verantwortlich. Der Generator hat darauf keinen Zugriff. Bei Fragen zur Website erreichen Sie uns über die oben genannte E-Mail-Adresse.</p></section>
''')
print('3 static information pages generated.')
